# Generated by Django 4.1.1 on 2022-10-02 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=250, verbose_name='Razão Social ou Nome')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('field_name', models.EmailField(max_length=254)),
                ('nome_contato', models.CharField(blank=True, max_length=100, verbose_name='Contato Princiopal')),
                ('celular_contato', models.CharField(blank=True, max_length=30, verbose_name='Celular/WhatsApp do Cliente')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('banco', models.CharField(blank=True, max_length=10, verbose_name='Banco')),
                ('banco_codigo', models.CharField(blank=True, max_length=10, verbose_name='Código do Banco')),
                ('banco_agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('banco_conta', models.CharField(blank=True, max_length=20, verbose_name='Conta Corrente')),
                ('pix_conta', models.CharField(blank=True, max_length=20, verbose_name='Chave PIX')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_cliente', models.CharField(choices=[('pf', 'Pessoa Física'), ('revenda', 'Revenda')], default='bovino', max_length=15, verbose_name='Tipo de Cliente:')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cadastrado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável:')),
            ],
        ),
    ]
