# Generated by Django 4.1.1 on 2022-10-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='field_name',
            new_name='email',
        ),
    ]
