# Generated by Django 4.1.1 on 2022-10-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_field_name_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento_cliente',
            field=models.CharField(default='000000000000', max_length=20, verbose_name='CNPJ ou CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular_contato',
            field=models.CharField(blank=True, max_length=30, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contato Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('pf', 'Pessoa Física'), ('revenda', 'Revenda')], default='revenda', max_length=30, verbose_name='Tipo de Cliente:'),
        ),
    ]
