# Generated by Django 4.1.1 on 2022-10-02 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_remove_cliente_cnpj_remove_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(default='XXX-0000', max_length=30, verbose_name='Placa')),
                ('marca', models.CharField(max_length=250, verbose_name='Razão Social ou Nome')),
                ('modelo', models.CharField(default='000000000000', max_length=20, verbose_name='CNPJ ou CPF')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carro_cadastrado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável:')),
            ],
        ),
    ]
