# Generated by Django 4.1.1 on 2022-10-03 01:06

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='ENTRE COM A MARCA', max_length=50, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='ENTRE COM O NOME DO MODELO', max_length=50, verbose_name='Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
            ],
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='modelo', chained_model_field='modelo', on_delete=django.db.models.deletion.CASCADE, to='app.modelo'),
        ),
    ]
