# Generated by Django 4.1.1 on 2022-10-03 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_marca_modelo_alter_veiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='marca', help_text='Selecione o modelo do veículo', on_delete=django.db.models.deletion.CASCADE, to='app.modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(help_text='Entre com a placa, apenas letras e números, sem espaços', max_length=30, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='responsavel',
            field=models.ForeignKey(help_text='Usuário responsável pelo cadastro', on_delete=django.db.models.deletion.CASCADE, related_name='carro_cadastrado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
    ]
