# Generated by Django 4.1.1 on 2022-10-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos-carros'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cadastrado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_dodcumento', models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('atraso', 'Em atraso'), ('despachante', 'Com Despachante'), ('pronto', 'Pronto')], default='novo', max_length=30, verbose_name='Status do Documento')),
                ('numeracao', models.CharField(help_text='Entre com a numeracao do documento', max_length=30, verbose_name='Numeracao')),
                ('anexo', models.FileField(blank=True, upload_to='anexo')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_documento', to='app.tipodocumento', verbose_name='Tipo de Documento')),
            ],
        ),
    ]
