# Generated by Django 4.1.1 on 2022-10-03 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_veiculo_foto_alter_cliente_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='app.veiculo', verbose_name='Veículo Relacionado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='anexo',
            field=models.FileField(blank=True, upload_to='documentos'),
        ),
    ]
