# Generated by Django 4.1.1 on 2022-10-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_documento_veiculo_alter_documento_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='app.cliente', verbose_name='Dono do Documento'),
        ),
    ]
