# Generated by Django 4.1.1 on 2022-10-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_documento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente', verbose_name='Dono do Documento'),
        ),
    ]
