# Generated by Django 4.1.1 on 2022-10-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_documento_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='cliente',
            new_name='dono_documento',
        ),
    ]
