# Generated by Django 4.1.1 on 2022-10-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_cliente_documento_dono_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='antigo_dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cliente', verbose_name='Antigo Donoe'),
            preserve_default=False,
        ),
    ]
