# Generated by Django 4.1.1 on 2022-10-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_veiculo_antigo_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='novo_dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novo_dono', to='app.cliente', verbose_name='Novo Dono'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='antigo_dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antigo_dono', to='app.cliente', verbose_name='Antigo Dono'),
        ),
    ]
